lib/phoenix_budget_web/router.ex
defmodule PhoenixBudgetWeb.Router do
  use PhoenixBudgetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixBudgetWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/budget/:id", BudgetController, :show
    get "/expenses", ExpensesController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixBudgetWeb do
  #   pipe_through :api
  # end
end

lib/phoenix_budget/application.ex
defmodule PhoenixBudget.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      PhoenixBudget.Repo,
      # Start the endpoint when the application starts
      PhoenixBudgetWeb.Endpoint
      # Starts a worker by calling: PhoenixBudget.Worker.start_link(arg)
      # {PhoenixBudget.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: PhoenixBudget.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    PhoenixBudgetWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/phoenix_budget/budget.ex
defmodule PhoenixBudget.Budget do
  use Ecto.Schema
  import Ecto.Changeset

  schema "budgets" do
    field :amount, :integer
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(budget, attrs) do
    budget
    |> cast(attrs, [:name, :amount])
    |> validate_required([:name, :amount])
  end
end

lib/phoenix_budget/budget_category.ex
defmodule PhoenixBudget.BudgetCategory do
  use Ecto.Schema
  import Ecto.Changeset

  schema "budget_category" do
    field :budget, :id
    field :category, :id

    timestamps()
  end

  @doc false
  def changeset(budget_category, attrs) do
    budget_category
    |> cast(attrs, [])
    |> validate_required([])
  end
end

lib/phoenix_budget/category.ex
defmodule PhoenixBudget.Category do
  use Ecto.Schema
  import Ecto.Changeset

  schema "categories" do
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(category, attrs) do
    category
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/phoenix_budget/expense.ex
defmodule PhoenixBudget.Expense do
  use Ecto.Schema
  import Ecto.Changeset

  schema "expenses" do
    field :amount, :float
    field :name, :string
    field :category, :id

    timestamps()
  end

  @doc false
  def changeset(expense, attrs) do
    expense
    |> cast(attrs, [:name, :amount])
    |> validate_required([:name, :amount])
  end
end

lib/phoenix_budget/repo.ex
defmodule PhoenixBudget.Repo do
  use Ecto.Repo,
    otp_app: :phoenix_budget,
    adapter: Ecto.Adapters.Postgres
end

lib/phoenix_budget_web/controllers/budget_controller.ex
defmodule PhoenixBudgetWeb.BudgetController do
  use PhoenixBudgetWeb, :controller

  alias PhoenixBudget.{Repo, Budget}

  def show(conn, %{"id" => id}) do
    render(conn, "index.html",
      id: id,
      budgets: Repo.all(Budget)
    )
  end
end

lib/phoenix_budget_web/controllers/expenses_controller.ex
defmodule PhoenixBudgetWeb.ExpensesController do
  use PhoenixBudgetWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/phoenix_budget_web/controllers/page_controller.ex
defmodule PhoenixBudgetWeb.PageController do
  use PhoenixBudgetWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/phoenix_budget_web/views/budget_view.ex
defmodule PhoenixBudgetWeb.BudgetView do
  use PhoenixBudgetWeb, :view
end

lib/phoenix_budget_web/views/error_view.ex
defmodule PhoenixBudgetWeb.ErrorView do
  use PhoenixBudgetWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/phoenix_budget_web/views/expenses_view.ex
defmodule PhoenixBudgetWeb.ExpensesView do
  use PhoenixBudgetWeb, :view
end

lib/phoenix_budget_web/views/layout_view.ex
defmodule PhoenixBudgetWeb.LayoutView do
  use PhoenixBudgetWeb, :view
end

lib/phoenix_budget_web/views/page_view.ex
defmodule PhoenixBudgetWeb.PageView do
  use PhoenixBudgetWeb, :view
  alias PhoenixBudgetWeb.Router.Helpers, as: Routes
  alias PhoenixBudgetWeb.Endpoint
end

lib/phoenix_budget_web/templates/budget/index.html.eex
<section class="phx-hero">
  <h1>Budget <%= @id %></h1>
  <h2>Total Budgets: <%= length(@budgets) %></h2>
</section>

lib/phoenix_budget_web/templates/expenses/index.html.eex
<section class="phx-hero">
  <h1>Expenses</h1>
</section>

lib/phoenix_budget_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>PhoenixBudget · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <a href="<%= Routes.page_path(PhoenixBudgetWeb.Endpoint, :index) %>">
          Home
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/phoenix_budget_web/templates/page/index.html.eex
<section class="row">
  <article class="column">
    <ul>
      <li>
        <a href="<%= Routes.budget_path(Endpoint, :show, 1) %>">First Budget</a>
      </li>
      <li>
        <a href="<%= Routes.expenses_path(Endpoint, :index) %>">Expenses</a>
      </li>
    </ul>
  </article>
</section>